// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvDXAKrRNjAaQIaMrjoM5eD1xJpZvaxc',
    appId: '1:728139696421:web:4e881fbc2d6068a11d72cc',
    messagingSenderId: '728139696421',
    projectId: 'flutter-starwars-app',
    authDomain: 'flutter-starwars-app.firebaseapp.com',
    storageBucket: 'flutter-starwars-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_-ANEfmSn6KzXMEJFD-Fl7G0mxXKGkw',
    appId: '1:728139696421:android:58fc65d9ad7f6e501d72cc',
    messagingSenderId: '728139696421',
    projectId: 'flutter-starwars-app',
    storageBucket: 'flutter-starwars-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgU-qsa5bZSMNt3DMczvT2p3N4Px_hsoU',
    appId: '1:728139696421:ios:5ea2621d123d243b1d72cc',
    messagingSenderId: '728139696421',
    projectId: 'flutter-starwars-app',
    storageBucket: 'flutter-starwars-app.appspot.com',
    iosClientId: '728139696421-lrno3mtsv369v24h6srmsjnhnmk6k5jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStarwarsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgU-qsa5bZSMNt3DMczvT2p3N4Px_hsoU',
    appId: '1:728139696421:ios:5ea2621d123d243b1d72cc',
    messagingSenderId: '728139696421',
    projectId: 'flutter-starwars-app',
    storageBucket: 'flutter-starwars-app.appspot.com',
    iosClientId: '728139696421-lrno3mtsv369v24h6srmsjnhnmk6k5jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStarwarsApp',
  );
}
